;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;					ASCII.INC						;
;					Include File					;
;				For printing ASCII strings			;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;Description: gives values to defined ASCII characters
;
;Revision History:	10/23/2014	Suzannah Osekowsky	initial revision

ASCIInull	EQU		00H;sets null to 00H
ASCIIzero 	EQU 	30H;Sets the ascii zero character to 30 hex
ASCIIminus	EQU		2DH;Defines ASCII minus character
ASCIIhexTen	EQU		41H;defines digits 10-15 to start at A